# Generated by Django 4.1.2 on 2022-12-06 07:29

from django.db import migrations, models
import django_dropbox_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(null=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='photos'),
        ),
    ]
