# Generated by Django 4.1.2 on 2022-11-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='NewsLetter',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
